USE [GameOfRevenge]
GO

/****** Object:  Table [dbo].[Friends]    Script Date: 6/5/2023 2:45:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE [dbo].[Friends](
	[FriendId] [BIGINT] IDENTITY(1,1) NOT NULL,
	[PlayerId] [int] NOT NULL,
	[FriendPlayerId] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
 CONSTRAINT [PK_FriendId] PRIMARY KEY CLUSTERED 
(
	[FriendId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_PlayerId_FriendPlayerId] UNIQUE NONCLUSTERED 
(
	[PlayerId] ASC,
	[FriendPlayerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Friends]  WITH CHECK ADD  CONSTRAINT [FK_PlayerId_Player_PlayerId] FOREIGN KEY([PlayerId])
REFERENCES [dbo].[Player] ([PlayerId])
GO

ALTER TABLE [dbo].[Friends] CHECK CONSTRAINT [FK_PlayerId_Player_PlayerId]
GO

ALTER TABLE [dbo].[Friends]  WITH CHECK ADD  CONSTRAINT [FK_FriendPlayerId_Player_PlayerId] FOREIGN KEY([FriendPlayerId])
REFERENCES [dbo].[Player] ([PlayerId])
GO

ALTER TABLE [dbo].[Friends] CHECK CONSTRAINT [FK_FriendPlayerId_Player_PlayerId]
GO


