namespace GameOfRevenge.Model
{
    public enum RoomParameterKey : byte
    {
        WorldId = 1,
        X = 2,
        Y = 3,
        PosPointX = 4,
        PosPointY = 5,
        Username = 6,
        CommonMessage = 7,
        IsSuccess = 8,
        LoginType = 9,
        PlayerId = 10,
        StructureId = 11,
        StructureLocationId = 12,
        StructureType = 13,
        StructureLevel = 14,
        ResourceId = 15,
        ResourceCollected = 16,
        BuildingBuildTime = 17,
        TotalTime = 18,
        TroopCount = 19,
        TroopType = 20,
        TroopLevel = 21,
        TrainingTime = 22,
        BoostUpTime = 23,
        Percentage = 24,
        TargetPlayerId = 25,
        AttackerId = 26,
        ReachedTime = 27,
        WinnerId = 28,
        Timestamp = 29,
        IsAttacking = 30,
        WoundedCount = 31,
        IsReturnFromAttack = 32,
        TechLevel = 33,
        TechType = 34,
        Hitpoint = 35,
        HeroIds = 36,
        QuestId = 37,
        QuestGroup = 38,
        Name = 39,
        QuestType = 40,
        Completed = 41,
        ProgressData = 42,
        InitialData = 43,
        InstantBuildCost = 44,
        SpeedUpCost = 45,
        HelpPower = 46,
        AllianceId = 47,
        KingLevel = 48,
        StartTime = 49,
        EnemyUsername = 50,
        ChatId = 51,
        ChatMessage = 52,
        Duration = 53,
        CastleLevel = 54,
        VIPPoints = 55,
        TroopsData = 56,
        HeroesData = 57,
        ResourceTotal = 58,
        WorkerId = 59,
        SetBoost = 60,
        Flags = 61
    }
}
